name: checkout

on: push

jobs:
  checkout-repo:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          repository: normanclt/code_migration
          ref: main

      - name: rsync version check
        run: rsync --version
