name: checkout

on: workflow_dispatch

jobs:
  checkout-repo:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: run commands
        run: |
          rsync --version
          ls -lrta
